### ISSUE TITLE
Valueless crossorigin attribute shouldn't be removed

### ISSUE THREAD

**Issue by jeffposnick** [wilsonzlin/minify-html#81] opened 2022-04-25 17:10 UTC
`<link crossorigin ...>` is equivalent to `<link crossorigin="anonymous" ...>`, but running that through `minify-html` results in `<link ...>`, which is not equivalent.

As per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin):

> Setting the attribute name to an empty value, like `crossorigin` or `crossorigin=""`, is the same as `anonymous`.

and

> By default (that is, when the attribute is not specified), CORS is not used at all.

I believe that https://github.com/wilsonzlin/html-data/blob/8e8f101df1641b50307d44e1469aad0fd2256e4a/data/data.json#L1091-L1110 needs to be changed, but I'm not entirely sure how that project's data is generated.

Without this change, minifying valid HTML written as `<link rel="preload" crossorigin ...>` will lead to, e.g., opaque preload responses that can't be used. (https://github.com/GoogleChrome/web.dev/issues/7770)

**Comment by wilsonzlin** [comment] 2022-04-26 02:59
Thanks for raising, I've made the changes into html-data. It turns out the React type definitions that the data is derived from does not consider `crossOrigin` a boolean attribute, which is why it considers the empty string redundant by default. This may be a bug in the types declaration, or intentional (e.g. force use of empty string). The fix will be part of the next version of minify-html.

I also had a look into the `<meta>` tag problem mentioned in the same linked issue, but couldn't immediately reproduce it (I quoted around the attribute value as the source input and minify-html did not remove the quotes). I'd be happy to look into it here (or in a new issue) as it does seem unexpected.

**Comment by jeffposnick** [comment] 2022-04-26 14:47
I was able to resolve the `<meta>` tag problem by opting-in to

```js
{
  do_not_minify_doctype: true,
  ensure_spec_compliant_unquoted_attribute_values: true,
  keep_spaces_between_attributes: true,
}
```

in our JavaScript configuration, so I'm not as worried about it.

(As an aside, I see that there's a `spec_compliant` configuration initializer [exposed in the Rust interface](https://docs.rs/minify-html/latest/minify_html/struct.Cfg.html#method.spec_compliant), but it's not clear whether the JavaScript bindings' `createConfiguration()` ends up calling that or not. Is there a difference between calling `createConfiguration()` with the options supplied above and using the `spec_compliant` initializer in Rust?)

**Comment by wilsonzlin** [comment] 2022-06-21 15:52
Awesome, good to hear that the issue is resolved. Version `0.8.1` also fixed the `crossorigin` attribute handling so it should no longer happen; let me know if it works on your end.

I've now updated the README to mention the options to keep the output spec-compliant more clearly. The `spec_compliant` method in Rust simply sets those fields in `Cfg` to true, and keeps the rest at `false`, so it's the same as providing them explicitly to `createConfiguration()` as you have described.

**Closed** 2022-06-21 15:52 UTC
