### ISSUE TITLE
Custom/vue template closing tags removed; `keep_closing_tags` ignored

### ISSUE THREAD

**Issue by jono-hayward** [wilsonzlin/minify-html#158] opened 2023-10-05 06:33 UTC
I've just identified this issue in our build process that uses minify-html. We use a lot of vue components mixed in with our markup, but minify-html seems to be very eager about removing the closing tags from some of these components. 

So something like this:
```Vue
<Tooltip x="center" y="below">
  <template #trigger>
    <Icon name="info" css="icon--sm" />
  </template>
  <template #content>
    <h3 class="font-sans text-sm font-semibold m-0">Note:</h3>
    <p class="text-sm m-0">Sed maxime alias sed id quis rerum voluptatum accusamus quod. Qui
      aspernatur id maxime quae et qui ut. Repudiandae nihil facilis inventore enim explicabo.
      Non neque et deserunt reiciendis occaecati est deserunt aut aut.</p>
  </template>
</Tooltip>
```

Becomes this:
```Vue
<tooltip x=left y=below> <template #trigger>
  <icon css=icon--sm name=info> <template #content>
      <h3 class="font-sans text-sm font-semibold m-0">Note:</h3>
      <p class="text-sm m-0">Quis itaque dolore dolor non exercitationem error id dolor dicta. Eveniet sed illo
        corporis cupiditate aut consequuntur error. Omnis unde vitae. Aperiam nulla voluptatem quis. Alias
        pariatur ad qui.</p>
    </template>
```

I've tried adding `keep_closing_tags: true` to the minifier config but this doesn't seem to make any difference to the output.

Any ideas? Am I just barking up the wrong tree hoping to use a minifer like this for custom markup?

**Comment by wilsonzlin** [comment] 2023-12-22 11:26
I did some digging into the provided example. I believe the issue is that `<Icon a=b />` is reinterpreted as `<Icon a=b>` i.e. the starting tag, as per the [parsing rules](https://github.com/wilsonzlin/minify-html/blob/master/notes/Parsing.md#tags). This causes all the following closing tags to be ignored *by the parser* (not dropped *by the minifier*), as mentioned in the parsing rules, because they don't match the opening tag. 

Self-closing tags aren't valid in HTML and browsers *typically* [reinterpret as an opening tag](https://html.spec.whatwg.org/multipage/parsing.html#self-closing-start-tag-state), although (as noted in the parsing rules) browsers have [far more complex logic](https://html.spec.whatwg.org/multipage/parsing.html) well outside the scope of this minifier. In this case, I would just change it to `<Icon a=b></Icon>`. Once changed, everything works fine, although the tag names get lowercased.

**Closed by wilsonzlin** 2023-12-22 11:26 UTC
